


service:
  input: SERVICE-A

component:
  input: COMPONENT-A
bil:
  test:
    a: "A"
    b: "B"
    c: "C"


---
spring:
  profiles: SENDONLY
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0
      batch-size: 1000
      retries: 0

application:
  properties:
    locations: "config"
service:
  input: SERVICE-A

component:
  input: COMPONENT-A
bil:
  test:
    a: "A"
    b: "B"
    c: "C"
